
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Sep 17 18:41:45 CEST 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 44;
  public static final int DIVIDE = 27;
  public static final int GREATER_OR_EQUAL = 21;
  public static final int INCREMENT = 16;
  public static final int CONST = 5;
  public static final int QUESTIONMARK = 48;
  public static final int CASE = 50;
  public static final int L_PAREN = 13;
  public static final int NOT_EQUAL = 19;
  public static final int GREATER = 20;
  public static final int SEMI = 7;
  public static final int CONTINUE = 33;
  public static final int NUM_CONST = 42;
  public static final int R_PAREN = 12;
  public static final int LESS = 22;
  public static final int MINUS = 25;
  public static final int DECREMENT = 17;
  public static final int LESS_OR_EQUAL = 23;
  public static final int COMMA = 8;
  public static final int R_SQUARE_BRACKET = 15;
  public static final int CLASS = 9;
  public static final int PLUS = 24;
  public static final int MULTIPLY = 26;
  public static final int IF = 40;
  public static final int DOT = 32;
  public static final int EOF = 0;
  public static final int RETURN = 37;
  public static final int EQUALS_TO = 18;
  public static final int EQUAL = 6;
  public static final int LOGICAL_OR = 29;
  public static final int NEW = 31;
  public static final int error = 1;
  public static final int MOD = 28;
  public static final int L_SQUARE_BRACKET = 14;
  public static final int IDENT = 43;
  public static final int BREAK = 34;
  public static final int VOID = 11;
  public static final int SWITCH = 47;
  public static final int COLON = 46;
  public static final int L_BRACE = 3;
  public static final int ELSE = 41;
  public static final int R_BRACE = 4;
  public static final int ENUM = 49;
  public static final int READ = 38;
  public static final int WHILE = 36;
  public static final int LOGICAL_AND = 30;
  public static final int EXTENDS = 10;
  public static final int PROG = 2;
  public static final int BOOL_CONST = 45;
  public static final int PRINT = 39;
  public static final int DO = 35;
}

